language: objective-c
#xcode_workspace: AutoNSCodingDemo/AutoNSCodingDemo.xcworkspace
#xcode_project: MyNewProject.xcodeproj # path to your xcodeproj folder
#xcode_scheme: AutoNSCodingDemoTests

before_install:
    - gem update
    - gem install cocoapods

script:
    - cd AutoNSCodingDemo
    - pod install
    - xctool clean build -workspace AutoNSCodingDemo.xcworkspace -scheme AutoNSCodingDemoTests -sdk iphonesimulator7.0