language: objective-c

before_install:
    - gem update
    - gem install cocoapods

script:
    - xctool test -sdk iphonesimulator7.0 -workspace AutoNSCodingDemo/AutoNSCodingDemo.xcworkspace -scheme AutoNSCodingDemoTests