language: objective-c

before_install:
    - gem update
    - gem install cocoapods

script:
    - cd AutoNSCodingDemo
    - pod install
    - xctool clean build test -sdk iphonesimulator7.0 -workspace AutoNSCodingDemo.xcworkspace -scheme AutoNSCodingDemoTests